[2025-02-11T17:09:35.581+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T17:09:35.615+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T17:09:31.863998+00:00 [queued]>
[2025-02-11T17:09:35.632+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T17:09:31.863998+00:00 [queued]>
[2025-02-11T17:09:35.635+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T17:09:35.662+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-02-11 17:09:31.863998+00:00
[2025-02-11T17:09:35.679+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1457) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T17:09:35.682+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-02-11T17:09:31.863998+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp_h7st65y']
[2025-02-11T17:09:35.685+0000] {standard_task_runner.py:72} INFO - Started process 1459 to run task
[2025-02-11T17:09:35.689+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask is_weather_api_ready
[2025-02-11T17:09:35.791+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T17:09:31.863998+00:00 [running]> on host 78b4170648b8
[2025-02-11T17:09:35.995+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T17:09:31.863998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T17:09:31.863998+00:00'
[2025-02-11T17:09:36.002+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T17:09:36.058+0000] {baseoperator.py:421} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-02-11T17:09:36.062+0000] {http.py:139} INFO - Poking: /data/2.5/weather?q=Portland&appid=be4f9bb349abd9d54fc5e2328b0b21ca
[2025-02-11T17:09:36.100+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-02-11T17:09:36.408+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-02-11T17:09:36.442+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T17:09:36.445+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=manual__2025-02-11T17:09:31.863998+00:00, execution_date=20250211T170931, start_date=20250211T170935, end_date=20250211T170936
[2025-02-11T17:09:36.530+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T17:09:36.598+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-11T17:09:36.604+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
