[2025-02-12T21:07:02.764+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T21:07:02.810+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_pipeline.is_weather_api_ready manual__2025-02-12T21:06:58.007749+00:00 [queued]>
[2025-02-12T21:07:02.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_pipeline.is_weather_api_ready manual__2025-02-12T21:06:58.007749+00:00 [queued]>
[2025-02-12T21:07:02.840+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T21:07:02.868+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-02-12 21:06:58.007749+00:00
[2025-02-12T21:07:02.889+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T21:07:02.895+0000] {standard_task_runner.py:72} INFO - Started process 270 to run task
[2025-02-12T21:07:02.896+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_pipeline', 'is_weather_api_ready', 'manual__2025-02-12T21:06:58.007749+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpa21oc9vd']
[2025-02-12T21:07:02.903+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask is_weather_api_ready
[2025-02-12T21:07:03.012+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_pipeline.is_weather_api_ready manual__2025-02-12T21:06:58.007749+00:00 [running]> on host 46a30c5a81ce
[2025-02-12T21:07:03.276+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_pipeline' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T21:06:58.007749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T21:06:58.007749+00:00'
[2025-02-12T21:07:03.280+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T21:07:03.286+0000] {baseoperator.py:421} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-02-12T21:07:03.288+0000] {http.py:139} INFO - Poking: /data/2.5/weather?q=Portland&appid=be4f9bb349abd9d54fc5e2328b0b21ca
[2025-02-12T21:07:03.306+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-02-12T21:07:03.511+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-02-12T21:07:03.532+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T21:07:03.534+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_pipeline, task_id=is_weather_api_ready, run_id=manual__2025-02-12T21:06:58.007749+00:00, execution_date=20250212T210658, start_date=20250212T210702, end_date=20250212T210703
[2025-02-12T21:07:03.612+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T21:07:03.661+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T21:07:03.665+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
