[2025-02-11T22:44:04.971+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T22:44:04.989+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T22:44:03.035276+00:00 [queued]>
[2025-02-11T22:44:04.999+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T22:44:03.035276+00:00 [queued]>
[2025-02-11T22:44:05.000+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T22:44:05.017+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-02-11 22:44:03.035276+00:00
[2025-02-11T22:44:05.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T22:44:05.028+0000] {standard_task_runner.py:72} INFO - Started process 1112 to run task
[2025-02-11T22:44:05.028+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-02-11T22:44:03.035276+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp9koyyar6']
[2025-02-11T22:44:05.032+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask is_weather_api_ready
[2025-02-11T22:44:05.094+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T22:44:03.035276+00:00 [running]> on host dbef5e540f20
[2025-02-11T22:44:05.211+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T22:44:03.035276+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T22:44:03.035276+00:00'
[2025-02-11T22:44:05.214+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T22:44:05.237+0000] {baseoperator.py:421} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-02-11T22:44:05.238+0000] {http.py:139} INFO - Poking: /data/2.5/weather?q=Portland&appid=be4f9bb349abd9d54fc5e2328b0b21ca
[2025-02-11T22:44:05.251+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-02-11T22:44:05.372+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-02-11T22:44:05.387+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T22:44:05.388+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=manual__2025-02-11T22:44:03.035276+00:00, execution_date=20250211T224403, start_date=20250211T224404, end_date=20250211T224405
[2025-02-11T22:44:05.456+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T22:44:05.501+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-11T22:44:05.505+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
