[2025-04-18T18:30:31.893+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T18:30:31.935+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_to_snowflake.dbt_tasks.dbt_run manual__2025-04-18T18:11:45.599763+00:00 [queued]>
[2025-04-18T18:30:31.959+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_to_snowflake.dbt_tasks.dbt_run manual__2025-04-18T18:11:45.599763+00:00 [queued]>
[2025-04-18T18:30:31.962+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2025-04-18T18:30:32.010+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_run> on 2025-04-18 18:11:45.599763+00:00
[2025-04-18T18:30:32.028+0000] {standard_task_runner.py:72} INFO - Started process 2426 to run task
[2025-04-18T18:30:32.038+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_api_to_snowflake', 'dbt_tasks.dbt_run', 'manual__2025-04-18T18:11:45.599763+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake_pipeline.py', '--cfg-path', '/tmp/tmpdfkb5qfw']
[2025-04-18T18:30:32.049+0000] {standard_task_runner.py:105} INFO - Job 271: Subtask dbt_tasks.dbt_run
[2025-04-18T18:30:32.189+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_api_to_snowflake.dbt_tasks.dbt_run manual__2025-04-18T18:11:45.599763+00:00 [running]> on host b322df8cb9fb
[2025-04-18T18:30:32.337+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_to_snowflake' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T18:11:45.599763+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T18:11:45.599763+00:00'
[2025-04-18T18:30:32.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-18T18:30:32.381+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T18:30:32.385+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --project-dir /opt/dbt --profiles-dir /opt/dbt']
[2025-04-18T18:30:32.417+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T18:30:39.549+0000] {subprocess.py:106} INFO - [0m18:30:39  Running with dbt=1.9.4
[2025-04-18T18:30:42.193+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-18T18:30:42.200+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-18T18:30:42.227+0000] {process_utils.py:132} INFO - Sending 15 to group 2426. PIDs of all processes in the group: [2428, 2426]
[2025-04-18T18:30:42.237+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2426
[2025-04-18T18:30:42.242+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-18T18:30:42.246+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-04-18T18:30:42.318+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-18T18:30:42.380+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2428, status='terminated', started='18:30:32') (2428) terminated with exit code None
[2025-04-18T18:30:42.395+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2426, status='terminated', exitcode=0, started='18:30:31') (2426) terminated with exit code 0
