[2025-02-11T23:32:13.901+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T23:32:13.941+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T23:32:09.801377+00:00 [queued]>
[2025-02-11T23:32:13.959+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T23:32:09.801377+00:00 [queued]>
[2025-02-11T23:32:13.961+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T23:32:13.998+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2025-02-11 23:32:09.801377+00:00
[2025-02-11T23:32:14.011+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1657) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T23:32:14.017+0000] {standard_task_runner.py:72} INFO - Started process 1659 to run task
[2025-02-11T23:32:14.016+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2025-02-11T23:32:09.801377+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp25iyfr_h']
[2025-02-11T23:32:14.025+0000] {standard_task_runner.py:105} INFO - Job 86: Subtask is_weather_api_ready
[2025-02-11T23:32:14.156+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2025-02-11T23:32:09.801377+00:00 [running]> on host dbef5e540f20
[2025-02-11T23:32:14.374+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T23:32:09.801377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T23:32:09.801377+00:00'
[2025-02-11T23:32:14.386+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T23:32:14.418+0000] {baseoperator.py:421} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-02-11T23:32:14.420+0000] {http.py:139} INFO - Poking: /data/2.5/weather?q=Portland&appid=be4f9bb349abd9d54fc5e2328b0b21ca
[2025-02-11T23:32:14.446+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-02-11T23:32:14.599+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-02-11T23:32:14.620+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T23:32:14.623+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=manual__2025-02-11T23:32:09.801377+00:00, execution_date=20250211T233209, start_date=20250211T233213, end_date=20250211T233214
[2025-02-11T23:32:14.691+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T23:32:14.771+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-11T23:32:14.775+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
